When a variable that has been renamed turns out not to be found, print both the 'current' and 'original' name.
Previous to this change, debugging could be very confusing - Converge would say "$$21$$" not found at line X where the user would see that there was a variable z. This patch now reports messages such as the following:

  Error: Line 5, column 17: Unknown variable '$$21$$' (renamed from 'z').